name: CI

on: pull_request
#on: [push, pull_request]

permissions:
  contents: read

jobs:
  checkers:
    name: Run static checkers
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: Run clang-format style check (.c and .h)
      uses: jidicula/clang-format-action@c74383674bf5f7c69f60ce562019c1c94bc1421a # v4.13.0
      with:
        clang-format-version: 17
        exclude-regex: '^\./deps/|^\./tests/|^\./utils/'
        # check-path: src
      # uses: jidicula/clang-format-action@f62da5e3d3a2d88ff364771d9d938773a618ab5e # v4.11.0
