name: Reply-schemas linter

on:
  push:
    paths:
      - 'src/commands/*.json'
  pull_request:
    paths:
      - 'src/commands/*.json'

permissions:
  contents: read

jobs:
  reply-schemas-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Setup nodejs
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      - name: Install packages
        run: npm install ajv
      - name: linter
        run: node ./utils/reply_schema_linter.js

